version: "3"

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - 5432:5432
    volumes:
      - ./docker/postgres/data/:/var/lib/postgresql/data/
    networks:
      - backend

  app:
    build:
      context: ./
    ports:
      - 5000:${EXPRESS_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80
    networks:
      - backend
      
networks:
  backend:
    driver: bridge
